apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: cors
  labels:
    purpose: cors
spec:
  headers:
    accessControlAllowOriginList:
      - "https://dev.asiayo.com"
    accessControlAllowMethods:
      - OPTIONS
      - GET
      - POST
      - PUT
      - DELETE
    accessControlAllowHeaders:
      - '*'
      - 'Content-Type'
    accessControlAllowCredentials: true
    addVaryHeader: true
    accessControlMaxAge: 100
