apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
# - ../../../base/middleware/redirect-scheme
# - ../../../base/middleware/redirect-slash
# - ../../../base/middleware/path-prefix
- ./ingressRoute.yml

labels:
- includeSelectors: true
  pairs:
    asiayo.com/app: route
    asiayo.com/product: example-product
