apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: example

resources:
- ../../../base/deployment
- ../../../base/service
- ../../../base/pdb
- ../../../base/hpa

labels:
- includeSelectors: true
  pairs:
    asiayo.com/app: nodejs
    asiayo.com/product: example-product

images:
- name: image
  newName: 48763/nodejs-sample
  newTag: latest

patches:
- patch: |-
    - op: replace
      path: /metadata/name
      value: nodejs
  target:
    kind: .*
- patch: |-
    - op: replace
      path: /spec/template/spec/containers/0/name
      value: nodejs
  target:
    kind: Deployment
- patch: |-
    - op: replace
      path: /spec/template/spec/containers/0/ports/0/containerPort
      value: 8080
  target:
    kind: Deployment
- patch: |-
    - op: remove
      path: /spec/replicas
  target:
    kind: Deployment
- patch: |-
    - op: replace
      path: /spec/scaleTargetRef/name
      value: nodejs
  target:
    kind: HorizontalPodAutoscaler
