server {
    listen 80;

    # 探針 endpoint:無條件回 200(liveness 的設計原則:能回應 = 活著)
    location = /livez           { access_log off; return 200 'ok'; }
    location = /readyz          { access_log off; return 200 'ok'; }
    location = /healthz/startup { access_log off; return 200 'ok'; }

    # 靜態頁
    location / {
        root  /usr/share/nginx/html;
        index index.html;
    }
}
