apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: example

resources:
- static-content.yml

labels:
- includeSelectors: true
  pairs:
    asiayo.com/app: nginx
    asiayo.com/product: example-product
